### Gradle settings

org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

### MDK configuration

parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.21)
forge_version=47.4.16
forge_version_range=[47.4.16,)
loader_version_range=[47,)

### Mod properties

mod_id=evolutioncore
mod_name=Project Evolution Core
mod_license=MIT License
mod_version=1.0.38
mod_group_id=io.github.createtechified.evolutioncore
mod_authors=wrldmap, pineapple
mod_description=EvolutionCore \nhello

### Dependencies

gtm_version=7.5.3
ae2cosmolite_version=15.4.10-cosmolite.38
guideme_version=20.1.14
patchouli_version=1.20.1-85-FORGE
ldlib_version=1.0.40.b
registrate_version=MC1.20-1.3.11
architectury_version=9.2.14
rhino_version=2001.2.3-build.10
kubejs_version=2001.6.5-build.26
create_version=6.0.8-289
ponder_version=1.0.91
flywheel_version=1.0.5
emi_version=1.1.22

## Ranges

gtm_version_range=[7.5.3,)
kjs_version_range=[2001.6.5-build.26,)
create_version_range=[6.0.8,6.1.0)
tinkers_version_range=[3.11.2.166,)